name: main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - run: sudo npm install -G gulp-cli
      
      - run: gulp