name: main
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - run: sudo npm install -G gulp-cli

      - run: gulp

      - uses: actions/upload-artifact@v2
        with:
          name: graphis-download-firefox
          path: dist