name: main
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: npm install

      - run: npm run release

      - uses: actions/upload-artifact@v3
        with:
          name: graphis-download-firefox
          path: out/graphis-download-firefox.xpi

